# Generated by Django 4.2.9 on 2024-02-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation_app", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="confirmation",
            field=models.CharField(default="False", max_length=20),
        ),
        migrations.AddField(
            model_name="book", name="guests", field=models.IntegerField(default=1),
        ),
    ]
