# Generated by Django 4.2.9 on 2024-02-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation_app", "0003_book_confirmation_book_guests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="time", field=models.TimeField(default="12:30:00"),
        ),
    ]
