# Generated by Django 4.2.9 on 2024-02-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation_app", "0004_alter_book_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="confirmation",
            field=models.CharField(default="Nein", max_length=20),
        ),
    ]
