# Generated by Django 4.2.9 on 2024-02-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation_app", "0005_alter_book_confirmation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="guests", field=models.IntegerField(default=""),
        ),
    ]
