# Generated by Django 4.2.9 on 2024-02-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation_app", "0006_alter_book_guests"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
