# Generated by Django 4.2.9 on 2024-02-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation_app", "0007_book_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book", old_name="name", new_name="last_name",
        ),
        migrations.AddField(
            model_name="book",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
