# Generated by Django 4.2.9 on 2024-03-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation_app",
            "0008_rename_name_book_last_name_book_fcm_token_book_phone",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="comment",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="decoration",
            field=models.BooleanField(default=False),
        ),
    ]
