# Generated by Django 4.2.9 on 2024-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation_app", "0009_book_comment_book_decoration"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="color",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
